### ISSUE TITLE
OSX: errors when compiling

### ISSUE THREAD

**Issue by leomil72** [Megatokio/zasm#13]
I tried to compile zasm 4.2.8 under OSX 10.15.4 Catalina. I got errors about the lack of symbols for x86_64:
`ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [zasm] Error 1`

Just launched the compilation with "make".

**Comment by leomil72** [comment]
A couple of more info:
`g++ -Wl -m64      -o zasm Error.o Label.o main.o Segment.o Source.o Z80Assembler.o CharMap.o helpers.o outputfile.o listfile.o Z80Header.o Macro.o Value.o zx7.o SyntaxError.o cstrings.o exceptions.o FD.o tempmem.o files.o z80_clock_cycles.o z80_major_opcode.o z80_opcode_length.o kio.o WavFile.o audio.o -lpthread -lz
Undefined symbols for architecture x86_64:
  "z180_clock_cycles(unsigned char, unsigned char, unsigned char)", referenced from:
      z80_clock_cycles(unsigned char, unsigned char, unsigned char, CpuID) in z80_clock_cycles.o
  "z180_opcode_can_branch(unsigned char, unsigned char)", referenced from:
      z80_opcode_can_branch(unsigned char, unsigned char, CpuID) in z80_clock_cycles.o
  "z180_clock_cycles_on_branch(unsigned char, unsigned char)", referenced from:
      z80_clock_cycles_on_branch(unsigned char, unsigned char, CpuID) in z80_clock_cycles.o
`

**Comment by Megatokio** [comment]
Thanks for the alert.
I fixed the Makefiles. Please try again.
And prease checkout the latests version of Libraries/ too.

**Comment by leomil72** [comment]
It's ok, now. Thank you:
`zasm - z80/8080 assembler (c) 1994 - 2020 Günter Woigk.`
` version 4.2.9, 2020-05-04, for Unix-MacOSX.`
