### ISSUE TITLE
macro args in --asm8080 mode

### ISSUE THREAD

**Issue by mk90** [Megatokio/zasm#14]
I found minor inaccuracy when processing macros in --asm8080 mode. This example source:
```
        org 0

c_m     MACRO   A
        LXI     D,&A
        ENDM

        c_m     SSS

SSS     DB      'TEST$';

        END
```
when trying to compile

`./zasm --asm8080 -i test.asm -o test.com 
`

falied:

```
in file test.asm:
4: 	LXI	D,&A
   	   	   ^ syntax error
assembled file: test.asm
    13 lines, 1 pass, 0.0012 sec.
    1 error

```
Error gone after changing macro args names with lowercase letters:

```
c_m     MACRO   a
        LXI     D,&A
        ENDM
```

It is because --casefold option is enabled automatically. Macro args stored in original case, but words in a macro body lowercased before searching in args array.

**Comment by Megatokio** [comment]
hello, 
it is fixed in latest commit for version 4.3.1.
thanks for the report. :-)
