### ISSUE TITLE
Compilation issue v4.4

### ISSUE THREAD

**Issue by alexeydixi** [Megatokio/zasm#20]
hello. 
When I tried to compile the zasm project I've got the error:

g++ -c -pipe -Os -Wall -W -fPIE -DNDEBUG -DRELEASE -Wno-multichar -std=c++11 -I. -ISource -ILibraries -o tmp/Value.o Source/Value.cpp
In file included from Source/Value.cpp:27:0:
Libraries/kio/kio.h:125:30: error: no ‘void Value::div(int32, Validity)’ member function declared in class ‘Value’
 #define throws noexcept(false)
                              ^
Source/Value.cpp:31:39: note: in expansion of macro ‘throws’
 void Value::div (int32 n, Validity v) throws
                                       ^~~~~~
Libraries/kio/kio.h:125:30: error: no ‘void Value::rem(int32, Validity)’ member function declared in class ‘Value’
 #define throws noexcept(false)
                              ^
Source/Value.cpp:45:39: note: in expansion of macro ‘throws’
 void Value::rem (int32 n, Validity v) throws
                                       ^~~~~~
make: *** [Makefile:66: tmp/Value.o] Error 1

OpenSuse Linux 15.1, g++ v7.5.0

How can I fix it ?

**Comment by Megatokio** [comment]
Hi,
this file is not part of the source, it's a left-over. you can delete it.
i will remove it from the archive too.

**Comment by alexeydixi** [comment]
thank you!
The project has been compiled after I deleted the file Source/Value.cpp
the file Source/Value.h still required.

**Comment by Megatokio** [comment]
yes, almost everything is in the header file.
actually i will not remove the .cpp file but use them again in operator/ and %. They just got lost during refactoring.
