### ISSUE TITLE
Hex based on org without #target

### ISSUE THREAD

**Issue by deltecent** [Megatokio/zasm#22]
I am attempting to assemble some Digital Research 8080 ASM.COM code and create a hex file. Although "-bin" is specified, zasm creates a ROM file and the hex file is based off address 0000 rather than org. Is it possible to have the hex file use org without having to use #target and break compatibility with ASM.COM? It seems "-rom" should make a rom hex file and "-bin" should make a binary hex file.

**Comment by Megatokio** [comment]
Hi,

do i understand you right you want to assemble the old source without modification, the source has an org != $0000 and you want the output to be an intel-hex file with addresses starting at that origin?

I think this is currently not possible. In general it's not possible to assemble source for any assembler just as it did, or even as we wish it should do now without touching the source. 

Command line options --bin and --hex select binary or a intel-hex output, they don't select target ram or rom. this is disjunct.
Target ram and rom make a difference for the addresses put in the hex file, and for target ram they start at the origin.

I could add a command line option for that. i'll consider that.

You could try this:

1) create a binary output file. can't you use that?

2) use a wrapper file:
`#target ram`
`#code myname, myorigin`
`#include "myfile.asm"`

3) touch the source. is it really so important?

kio !

**Comment by deltecent** [comment]
I'll try that solution. I work on software for the Altair 8800 using both ASM.COM under CP/M and also like to use zasm on my Mac, because it's much software. A common way of loading software on the Altair is using a ROM monitor that loads HEX files through a serial port. A lot of software has an ORG of 0100h because that's where CP/M loads things. If I add the #target and #code to the file, ASM.COM will no longer assemble it.

Not a bit deal. I can try the wrapper or just comment out those lines when using CP/M. I was curious is there was a way to too zasm to target ram rather than rom through a command line switch.

**Comment by Megatokio** [comment]
i have added a command line option "--target=ram".
could you please test it and tell me whether it works as expected.

**Comment by g3wyw** [comment]
Hi Kio,

I have the same problem!  I am using the RPi version of ZASM, on a Raspberry Pi Zero Wifi as a development platform for a RC2014 CP/M machine. ZASM runs very well on the Pi Zero.

Without the #target RAM directive at the top with the associated #code and #data directives, the .hex file compiles at address $0000 even though the .lst file shows the correct object code. I'm running V4.4.1 dated 19 Oct 2020..

The --target=ram command line option doesn't seem to work on my RPi version. 

Here are a couple of test examples for you. I use zasm -uwx testhex.asm to assemble. The .lst file shows the correct opcodes even though the #target and #code directives are commented out, but the associated .hex file (testhex_ng.hex) is built from location $0000. Enabling the #directives and commenting out my .org directive and using the same -uwx options builds the hex file correctly. (testfile_ok.hex).

I'd be happy to include the #target=ram directive at the top of the source code, to generate correct .hex files, but its the requirement to add the #code and #data segments that makes it difficult to use for old Z80 and 8080 code. 

Best Regards 

Paul
[testhex.zip](https://github.com/Megatokio/zasm/files/6049767/testhex.zip)

**Comment by Megatokio** [comment]
Hi Paul,
can you compile zasm from source? this fix was added in version 4.4.6.

update: i compiled zasm 4.4.7 for Raspios on armhf but can't test it on real hardware.
please get it from https://k1.spdns.de/Develop/Projects/zasm/Distributions/ 
and tell me, whether it works for you.

thanks!

**Comment by g3wyw** [comment]
Hi Kio,
Thanks for reply. I have downloaded the V4.4.7 and installed it OK. Runs fine on the RPi Zero WiFi and builds my test code the same as before but using the --target=ram invokes the help file with no build
$zasm -uwx testhex.asm with no #target ram or #code or #data directives in the source builds  .rom file with intel hex at $0000. Note -x appears to be ignored?
$zasm --target=ram testhex.asm prints the help file and doesnt build anything.
$zasm -uwx testhex.asm with the #target ram and a #code page1, $A123, * directive in the source builds a .hex file correctly with correct addresses and opcodes in the list file as expected.

Sorry, I don't have a build environment. My RPi Zero only has a cli interface. no X. I connect remotely using SSH within my network. Works fine. Any help appreciated. Its surprisingly fast building a 64K Z80 CP/M and a BIOS in around 3 seconds. 

BR Paul

**Comment by Megatokio** [comment]
hi Paul,
that's puzzling. indeed command line option "--target=ram" does not work, i fixed the cause right now.
i investigate the problem with "-x" for legacy code without "#target ..."
Kio !

**Comment by Megatokio** [comment]
ok, i have fixed the error.
new version 4.4.8 is available for amd64 and arm32 Linux.
please get it from https://k1.spdns.de/Develop/Projects/zasm/Distributions/ and test it. :-)

speed: yes, even slow computers nowadays are much faster than fast computers ~40 years ago. :-)
most sources on my desktop Linux assemble in a few milliseconds only.

Kio !

**Comment by g3wyw** [comment]
Hi Kio,
Thanks for the latest version. Unfortunately its not doing what i expected. 
$zasm --target=ram  testhex.asm with no #directives in the source produces a .bin binary file.
$zasm -hex testhex.asm with no #directives in source produces a .hex file with load addr starting at $0
(the hex file is fine including calls to correct code. Its just the intel file load address that starts at zero that is wrong) 
Enabling the #directives ( #target ram and #code, page0, $A123,* and using 
$zasm -uwx testhex.asm builds correct .hex file and .lst file.
Appreciate your help in getting this fixed. 
If the -x or --hex command line could make the intel hex file load address be the same as the  code  build address it would be OK. Its a very powerful assembler and I like the way it works. 

BR Paul

**Comment by Megatokio** [comment]
Hi,
you must include both options, -x and --target=ram to get a hex file with addresses as set by .org
-x enables output of hex file instead of binary file
--target=ram set's the default target as with "#target ram" in source
Kio !

**Comment by g3wyw** [comment]
Hi Kio,

 

Bingo!!!!! Works fine. 

 

Thanks for a great job. 

 

Best Regards 

 

Paul
