### ISSUE TITLE
Made a win64 port.

### ISSUE THREAD

**Issue by turbocat2001** [Megatokio/zasm#26]
Ported Zasm for Windows x64. I compiled it in the Cygwin environment, so cygwin1.dll is needed. It is in the attached file. I attach patche
s and the assembled program. PS It would be nice if it was official.
[zasm-win64.zip](https://github.com/Megatokio/zasm/files/8251900/zasm-win64.zip)

**Comment by Megatokio** [comment]
thanks for the patch. :-)
I included it but made some small adjustments. 
Can you please checkout branch "cygwin" for zasm and Libraries/ and check whether it compiles?
The binary will be downloadable from the zasm homepage.
Kio !

**Comment by turbocat2001** [comment]
It's great that you accepted :). Actually, I needed the submodule to build packages using cygport. But then I changed my mind, since it is a very long procedure for publishing packages in the Cygwin repository. In any case, I'll check the functionality tomorrow. And I'll probably try to build it as win32.

**Comment by Megatokio** [comment]
thanks. i'm looking forward to it. :-)

**Comment by turbocat2001** [comment]
I checked your changes. Alas, they were not enough. This is how I made a pull request, it should fix everything. And I also managed to build zasm under win32
[zasm-win32.zip](https://github.com/Megatokio/zasm/files/8462404/zasm-win32.zip).

And you also need to update the submodule in the cygwin branch. To have a link to cygwin.

**Comment by Megatokio** [comment]
thanks a lot. i merged your changes into Libraries/master and updated zasm. The 2 binaries you compiled are available from my website [k1.spdns.de/](https://k1.spdns.de/Develop/Projects/zasm/Distributions/) 
Kio !
