### ISSUE TITLE
macOS Ventura (13.5.2) - zasm will not compile ... 

### ISSUE THREAD

**Issue by pfg504** [Megatokio/zasm#32]
Numerous errors trying to make latest version of zasm on macOS Ventura. I have tried several different flavors of makefile ....
Last was: 

CFLAGS      = -pipe -Os -Wall -W -fPIE $(DEFINES) -nostdinc

INCPATH     = -I. -ISource -ILibraries -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/Current/Headers
========
clang++ -c -pipe -Os -Wall -W -fPIE -DNDEBUG -DRELEASE -nostdinc -Wno-multichar -std=c++11 -I. -ISource -ILibraries -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/Current/Headers -o tmp/cstrings.o Libraries/cstrings/cstrings.cpp
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:56:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cassert:19:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__assert:14:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__verbose_abort:34:3: error: no member named 'abort' in the global namespace; did you mean simply 'abort'?
  ::abort();
  ^~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__verbose_abort:28:17: note: 'abort' declared here
extern "C" void abort();
                ^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:14:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:50:9: error: no member named 'nullptr_t' in the global namespace
using ::nullptr_t;
      ~~^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:421:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/invoke.h:17:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/decay.h:16:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_array.h:40:22: error: reference to unresolved using declaration
template <class _Tp, size_t _Np> struct _LIBCPP_TEMPLATE_VIS is_array<_Tp[_Np]>
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:421:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/invoke.h:17:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/decay.h:20:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/remove_extent.h:25:22: error: reference to unresolved using declaration
template <class _Tp, size_t _Np> struct _LIBCPP_TEMPLATE_VIS remove_extent<_Tp[_Np]>
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:16:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/type_list.h:28:28: error: reference to unresolved using declaration
template <class _TypeList, size_t _Size, bool = _Size <= sizeof(typename _TypeList::_Head)> struct __find_first;
                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:16:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/type_list.h:30:33: error: reference to unresolved using declaration
template <class _Hp, class _Tp, size_t _Size>
                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:16:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/type_list.h:36:33: error: reference to unresolved using declaration
template <class _Hp, class _Tp, size_t _Size>
                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:28:18: error: reference to unresolved using declaration
    static const size_t value = _LIBCPP_PREFERRED_ALIGNOF(_Tp);
                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:49:11: error: reference to unresolved using declaration
template <size_t _Align>
          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:52:22: error: reference to unresolved using declaration
template <class _TL, size_t _Align> struct __find_pod;
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:54:22: error: reference to unresolved using declaration
template <class _Hp, size_t _Align>
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:64:33: error: reference to unresolved using declaration
template <class _Hp, class _Tp, size_t _Align>
                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:74:22: error: reference to unresolved using declaration
template <class _TL, size_t _Len> struct __find_max_align;
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:76:22: error: reference to unresolved using declaration
template <class _Hp, size_t _Len>
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:77:83: error: reference to unresolved using declaration
struct __find_max_align<__type_list<_Hp, __nat>, _Len> : public integral_constant<size_t, _Hp::value> {};
                                                                                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:77:83: error: reference to unresolved using declaration
struct __find_max_align<__type_list<_Hp, __nat>, _Len> : public integral_constant<size_t, _Hp::value> {};
                                                                                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:79:11: error: reference to unresolved using declaration
template <size_t _Len, size_t _A1, size_t _A2>
          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:79:24: error: reference to unresolved using declaration
template <size_t _Len, size_t _A1, size_t _A2>
                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
In file included from Libraries/cstrings/cstrings.cpp:5:
In file included from Libraries/cstrings/cstrings.h:6:
In file included from Libraries/kio/kio.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/utility:225:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:428:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/aligned_storage.h:79:36: error: reference to unresolved using declaration
template <size_t _Len, size_t _A1, size_t _A2>
                                   ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:52:1: note: using declaration annotated with 'using_if_exists' here
using ::size_t _LIBCPP_USING_IF_EXISTS;
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [tmp/cstrings.o] Error 1

**Comment by Megatokio** [comment]
hello,
this seems more likely to be a configuration issue on your side. Are you able to compile any source? e.g. have you the Xcode command line tools installed?
Otherwise take a look into kio/auto_config.h and detect_configuration.h and check whether _UNIX etc. are correctly #defined. But i doubt that it has to do with any of the #defines here, because the error happens within the the very first #included files of each source file before they can make any difference.

**Comment by Megatokio** [comment]
seems the problem is solved? else reopen the issue.
kio !
