### ISSUE TITLE
ORG cannot be set back to lower address

### ISSUE THREAD

**Issue by pdr0663** [Megatokio/zasm#33]
Hi there.

I'm trying to port a Forth implementation to the ZX81. The Forth names are stored in a linked list which grows downwards in memory, but is linked forwards, so the last item entered is the lowest in memory, and the first item is the highest.

Im using #code NameSpace to identify this part of the code, and trying to use .phase to manipulate the current code location to begin each entry in the correct place. The code uses some variables to calculate the correct starting point of each entry, and .phase is used to effect the new starting point.

The problem is, it seems that the assembler is ignoring the .phase instruction. Is it a feature of the assembler that the code origin must always increase, and never decrease using .phase?

Paul

**Comment by Megatokio** [comment]
Hi Paul,
your understanding of .phase is wrong. See documentatioon for  [.phase](https://k1.spdns.de/Develop/Projects/zasm/Documentation/z71.htm#A). It changes the logical code address, not where it is stored.
A possible way to go for you is to use macros to create labels with a serial number so you can link them. see [.macro](https://k1.spdns.de/Develop/Projects/zasm/Documentation/z68.htm#A), esp. the last example, and move the .org. But storing code backwards is a challenge.
Kio !

**Comment by Megatokio** [comment]
Hi Paul,
thinking over it, either i have misunderstood your approach or it is a bad idea.
I suggest you write the words in sequence as they are stored in the rom, starting with the latest word. Then you have one block of code which you want to end at the predefined top of the library. Now the only challenge is to get the start address for this block, because you end up subtracting two not-yet-defined labels, though a human can tell that the difference could be calculated.
I think the best is to put it in a #code segment, as you already do. Then you can get the total size from a label defined by the assembler: NameSpace_size which you can use in the calculation of the segment start address.
please tell me if this worked for you.
Kio !

**Comment by pdr0663** [comment]
Kio,

Firstly, thanks for your prompt and detailed reply.

The code is a legacy of eForth, and I'm reluctant to change it. Here is the macro to create the header for each Forth word. It contains the code I mentioned inmy question above:

`
CODE    MACRO   LEX,NAME,LABEL
LABEL:                                  ;;assembly label
        CODE_ = $$                      ;;save code pointer
#code   NameSpace
        _LEN    = (LEX AND 01FH)/CELLL  ;;string cell count, round down
        NAME_   = NAME_-((_LEN+3)*CELLL);;cell boundary, downward
        .phase  NAME_                   ;;set name pointer
        DW      CODE_,LINK_             ;;token pointer and link
        LINK_   = $$                    ;;link points to a name string
        DB      LEX,NAME                ;;name string
#code   CodeSpace
        ;.phase  CODE_                  ;;restore code pointer
        ENDM
`

CodeSpace and NameSpace are initialized elsewhere with another #code statement, and the intitial location, before calling this macro. As mentioned above, the code and names live in separate areas of memory, and grow towards each other, like two opposed stacks. The code growas upwards in the normal sense, and the names grow downwards from a starting point higher in memory. It is a little unusual in Forth, but it's an internal feature of eForth.

I'm not familiar with the concept of #code and #data segments, although I see they are a concept from the Unix C world. I do understand that concept. I have only used ORG as the means of setting the current location, and the code I'm porting was writted for Microsoft's MASM. I chose ZASM as I could run under Windows (with CygWin), and it supports macros in a similar syntax to MASM. MASM allows ORG to change the current execution address at will, forwards or backwards without limitation, it seems.

Here is the original legacy code:

`
$CODE   MACRO   LEX,NAME,LABEL
        $ALIGN                            ;;force to cell boundary
LABEL:                                    ;;assembly label
        _CODE   = $                       ;;save code pointer
        _LEN    = (LEX AND 01FH)/CELLL    ;;string cell count, round down
        _NAME   = _NAME-((_LEN+3)*CELLL)  ;;cell boundary, downward
ORG     _NAME                             ;;set name pointer
        DW       _CODE,_LINK              ;;token pointer and link
        _LINK   = $                       ;;link points to a name string
        DB      LEX,NAME                  ;;name string
ORG     _CODE                             ;;restore code pointer
        ENDM
`

Note that ALIGN is used in the code, as this Z80 version was originally ported from an 8086 version. I understand ALIGN is redundant on the Z80, as loads can occur at any address, please correct me if I'm wrong.

Can I do something similar to the legacy code with ZASM, in a way you may know?

Paul

**Comment by pdr0663** [comment]
In case you can't read the code above, here it is outside of a <cpde> block.

CODE    MACRO   LEX,NAME,LABEL
LABEL:                                  ;;assembly label
        CODE_ = $$                      ;;save code pointer
#code   NameSpace
        _LEN    = (LEX AND 01FH)/CELLL  ;;string cell count, round down
        NAME_   = NAME_-((_LEN+3)*CELLL);;cell boundary, downward
        .phase  NAME_                   ;;set name pointer
        DW      CODE_,LINK_             ;;token pointer and link
        LINK_   = $$                    ;;link points to a name string
        DB      LEX,NAME                ;;name string
#code   CodeSpace
        ;.phase  CODE_                  ;;restore code pointer
        ENDM



and


$CODE   MACRO   LEX,NAME,LABEL
        $ALIGN                            ;;force to cell boundary
LABEL:                                    ;;assembly label
        _CODE   = $                       ;;save code pointer
        _LEN    = (LEX AND 01FH)/CELLL    ;;string cell count, round down
        _NAME   = _NAME-((_LEN+3)*CELLL)  ;;cell boundary, downward
ORG     _NAME                             ;;set name pointer
        DW       _CODE,_LINK              ;;token pointer and link
        _LINK   = $                       ;;link points to a name string
        DB      LEX,NAME                  ;;name string
ORG     _CODE                             ;;restore code pointer
        ENDM

**Comment by pdr0663** [comment]
And here's a file with the same code....
[code.txt](https://github.com/Megatokio/zasm/files/13272325/code.txt)

**Comment by Megatokio** [comment]
What is the error with the original code? the only thing i can see is that ORG should not start in column 1. I assume that way it is interpreted as a label definition? this depends on --require_colon setting. with this option i cannot see why it didn't work.
Kio !

**Comment by Megatokio** [comment]
$ALIGN: this seems to be a macro. it depends on what this macro does.

**Comment by pdr0663** [comment]
I like your assembler, and I very much want to integrate my code into your ZX81 tape template (.p). Can the template function with just ORGs or will I need to come to terms with #code and .phase to do it?

Paul

**Comment by Megatokio** [comment]
Hi Paul,
now i see what the problem is. ORG is implemented by inserting space up to the new ORG. i didn't anticipate a use case where it is set backwards, because this normally results in overwriting already created code. setting it backwards results in inserting a negative number of spaces, which doesn't work. I'll work on a solution. 
Kio !

**Comment by Megatokio** [comment]
@ .p file:
i think it can all go into one segment and you don't need .phase.

**Comment by Megatokio** [comment]
I have changed some code and think that setting ORG back to lower address is now possible. As i cannot compile it for Windows for myself, can you test it with the online assembler? [k1.spdns.de/cgi-bin/zasm.cgi](https://k1.spdns.de/cgi-bin/zasm.cgi)

If it works i will alert a helpful hand to create the Windows version. btw. can you compile the source?
Kio !

**Comment by Megatokio** [comment]
can you test it with the online assembler? [k1.spdns.de/cgi-bin/zasm.cgi](https://k1.spdns.de/cgi-bin/zasm.cgi)
thanks,
Kio !

**Comment by pdr0663** [comment]
Sorry for my slow reply.



I have used a workaround, suggest by you above. I've used serial numbered #code areas, which happily jump back and forth. 

> can you test it with the online assembler? [k1.spdns.de/cgi-bin/zasm.cgi](https://k1.spdns.de/cgi-bin/zasm.cgi) thanks, Kio !

Won't assemble, gives this result:

```
tempmem: single-threaded ../Source/listfile.cpp:425: assert failed: !segment \|\| !segment->size.is_valid() \|\| sourceline.bytecount <= 0x10000 aborted.
```

**Comment by pdr0663** [comment]
I managed to work around the problem by avoiding ORGs and using serial #code labels.

I'm using the ZX81 "tape" template, and I now get this issue:

```
in file efz80-zx81.asm:
2682:         ; (RAMTOP)              End of memory (address of last byte (incl.))
      ^ segment SYSVARS: E_LINE must match ram end address $4074 (E_LINE=$5B5D)
assembled file: efz80-zx81.asm
    5398 lines, 6 passes, 0.1669 sec.
    1 error
```

Is the assembler aware of the ZX81 system variables, and is not happy with the value of E_LINE?

Paul

**Comment by pdr0663** [comment]
> I have changed some code and think that setting ORG back to lower address is now possible. As i cannot compile it for Windows for myself, can you test it with the online assembler? [k1.spdns.de/cgi-bin/zasm.cgi](https://k1.spdns.de/cgi-bin/zasm.cgi)
> 
> If it works i will alert a helpful hand to create the Windows version. btw. can you compile the source? (branch 'allow_org_going_back') Kio !

Thanks much appreciated. However, I'm using the ZX81 tape template, which uses #code for the various ZX81 spaces, and I assume I'll need to integrate into that using #code for my stuff. Correct me if I'm wrong.

**Comment by Megatokio** [comment]
> Sorry for my slow reply.
> I have used a workaround, suggest by you above. I've used serial numbered #code areas, which happily jump back and forth.
> > can you test it with the online assembler? [k1.spdns.de/cgi-bin/zasm.cgi](https://k1.spdns.de/cgi-bin/zasm.cgi) thanks, Kio !
> Won't assemble, gives this result:
> ```
> tempmem: single-threaded ../Source/listfile.cpp:425: assert failed: !segment \|\| !segment->size.is_valid() \|\| sourceline.bytecount <= 0x10000 aborted.
> ```

ok, there is a test for the number of bytes added by one instruction for including in the listing, and setting the ORG back makes a negative number. even for positive offset the listing is a little bit silly. it should compact the hufe number of FFs. 
this can be fixed.

**Comment by Megatokio** [comment]
> I managed to work around the problem by avoiding ORGs and using serial #code labels.
> I'm using the ZX81 "tape" template, and I now get this issue:
> ```
> 2682:         ; (RAMTOP)              End of memory (address of last byte (incl.))
>       ^ segment SYSVARS: E_LINE must match ram end address $4074 (E_LINE=$5B5D)
> assembled file: efz80-zx81.asm
> ```
> Is the assembler aware of the ZX81 system variables, and is not happy with the value of E_LINE?

actually yes. by setting #target=p81 zasm knows about some peculiarities which it cares about. and without setting E_LINE to the correct address your program won't load successfully.
This is required by the ZX81 tape loading routine, not by zasm.

**Comment by Megatokio** [comment]
> Thanks much appreciated. However, I'm using the ZX81 tape template, which uses #code for the various ZX81 spaces, and I assume I'll need to integrate into that using #code for my stuff. Correct me if I'm wrong.

no, that is not required. you can just set #target or not even that.
The template simply contains the definitions for the various system variables at the right place. 
Starting with ORG $4009 and jumping around with subsequent ORGs will be ok. segments are just for organizing. 

Because the error is in the list file generation and i assume only if the object code is included, you can already use the online assembler without listing the object code.
I'll fix the problem in the list file generation so you can do another test with object code.
Kio !

**Comment by pdr0663** [comment]
> actually yes. by setting #target=p81 zasm knows about some peculiarities which it cares about. and without setting E_LINE to the correct address your program won't load successfully. This is required by the ZX81 tape loading routine, not by zasm.

```
2682:         ; (RAMTOP)              End of memory (address of last byte (incl.))
      ^ segment SYSVARS: E_LINE must match ram end address $4074 (E_LINE=$5B5D)
assembled file: efz80-zx81.asm
```

I still don't understand the error. E_LINE is set to a label located in the source where E_LINE should point (E_LINE=$5B5D) as I understand. E_LINE is after the REM statement, display file etc, according to the template file. $4074 seems to me to refer to an undocumented area in the ZX81 system variables. Is the error indicating that $5B5D should be stored in location $4074?

Paul

**Comment by Megatokio** [comment]
hm, i think this is a result of setting the ORG back. zasm probably compares E_LINE with the current code pointer which is presumably pointing somewhere inside the code. I'll check this.
Kio !

**Comment by Megatokio** [comment]
I have updated the online assembler. please give it another try. 
Kio !

**Comment by Megatokio** [comment]
btw., if the library headers are at the end of ram and you save this as a .p tape file, isn't then a whole lot of empty space included in the tape file?
Kio !

**Comment by pdr0663** [comment]
> btw., if the library headers are at the end of ram and you save this as a .p tape file, isn't then a whole lot of empty space included in the tape file? Kio !

I'm a little ignorant about what actually gets saved onto the tape file. I assume that it is everything from $4009 up to but not including E_LINE, as what follows in the BASIC system is stacks etc which are dynamic. That's consistent with the .p template. I understand the BASIC system upon boot-up scans available RAM and sets RAMTOP to the first byte above the top. The GOSUB and machine stacks are placed immediately under RAMTOP, and there is a large space down to the STKEND which is the upper end of the calculator stack. I've verified this by POKEing the system variables on a 16k system.

BTW if by "library headers' you're referring to the names in the example I've provided, they are located near the end of the REM statement, and grow downwards towards the compiled Forth code, which is growing upwards. This is an oddity of eForth, most other Forths have a unified name and code structure, and grow in one direction. In eForth, there is necessarily some free space between the name and code spaces, to allow for new names and new code. This is effectively the working space of the eForth system, and I assume would need to be present in the tape file.

Paul

**Comment by pdr0663** [comment]
Ok, it seems to assemble just fine now. For the Eighty-One emulator, I guess I target "p", right? Can I please download the source or CygWin compiles executable?

**Comment by Megatokio** [comment]
.p or .81 both will be ok.

i'll get the cygwin binary compiled, but can't say in advance how long it will take. one day i'll dive into this yaml stuff to make an action to compile it on github, but not today.
download the source: you are at the source. at the zasm start page click on the `CODE` button. if you clone with git take care the `Libraries`submodule is clone too. If you download the zip download the zip for Libraries too and place it's contents in the `Libraries` folder inside the zasm source. The Makefile works out of the box on my Linux, i expect it to work on Cygwin too. 
Kio !

**Comment by Megatokio** [comment]
btw. the approach with one #code segment per word works fine but has an interesting catch: zasm allocates 64k per segment, which is normally no problem, but if you have 100 words this means 6.4MB. :-) no problem nowadays thou.
Kio !

**Comment by pdr0663** [comment]
Thanks. The code assembles fully and the listing looks good, seems 100% with addresses etc. The only problem: EightyOne won't load it as a tape. It loads partially then EightyOne just retuirns to the 0/0 prompt.

I dis a hello world style program based on your zx81 template, and it also will not run on the EightyOne. Can you tell me if there's something odd with my file?

```
#target p81
#charset ZX81
; only if target p81:
#if target(p81)
#code _PROGNAME
        dm      "TEST" | $80        ; this will be translated by zasm into the ZX81 character set!
#endif

; ================================================================
;       Example source with target 'p' or '81'
;       ZX81 tape file / snapshot
;       Copyright  (c)  Günter Woigk 1994 - 2017
;                                       mailto:kio@little-bat.de
; ================================================================

; ---------------------------------------------------------------
;                                       Memory Map
; ---------------------------------------------------------------
;
; 16509    - (D_FILE)   Basic Program
; (D_FILE) - (VARS)     Display File (Screen)
; (VARS)   - (E_LINE)   Basic Variables; last byte at (E_LINE)-1 = $80
; (E_LINE) - (STKBOT)   Line being typed and work space
; (STKBOT) - (STKEND)   Calculator Stack
; (STKEND) - (ERR_SP)   Spare space and Z80 Machine Stack (sp)
; (ERR_SP) - (RAMTOP)   Gosub Stack
; (RAMTOP)              End of memory (address of last byte (incl.))
;
; value of RAMTOP:
;       $43FF = 17407 For 1k internal ram (ZX81)
;       $47FF = 18431 For 2k internal ram (TS1000)
;       $7fff = 32767 for 16k Ram Pack
;       $bfff = 49151 for 32k Ram Pack
;       $ffff = 65535 for 64k Ram Pack


; ---------------------------------------------------------------
; THE SYSTEM VARIABLES
; Source: ZX81 BASIC Programming by Steven Vickers, (c) Sinclair Research Limited
; ---------------------------------------------------------------
;
; SYSVARS $4000 - $4008 which are not saved to tape by the ZX81:

#data SYSVARS_NOT_SAVED, $4000, 9

ERR_NR: db  0       ; 4000      1 less than the report code. Starts off at 255 (for -1), so PEEK 16384, if it works at all, gives 255.
                    ;           POKE 16384,n can be used to force an error halt: 0 … 14 gives one of the usual reports,
                    ;           15 … 34 or 99 … 127 gives a nonstandard report, and 35 … 98 is likely to mess up the display file.
FLAGS:  db  0       ; 4001  X   Various flags to control the BASIC system.
ERR_SP: dw  0       ; 4002  X   Address of first item on machine stack (after GOSUB returns).
RAMTOP: dw  0       ; 4004      Address of first byte above BASIC system area. You can poke this to make NEW reserve space above
                    ;           that area (see Chapter 26) or to fool CLS into setting up a minimal display file.
                    ;           Poking RAMTOP has no effect until one of these two is executed.
MODE:   db  0       ; 4006  N   Specifies K, L, F or G cursor.
PPC:    dw  0       ; 4007  N   Line number of statement currently being executed.
                    ;           Poking this has no lasting effect except in the last line of the program.


; SYSVARS $4009 - $403B which are saved in the tape file:

#code SYSVARS, $4009, $407D-$4009

VERSN:  db  0       ; 4009      0 identifies 8K ZX81 Basic in saved programs.
E_PPC:  dw  0       ; 400A      Number of current line (with program cursor).
D_FILE: dw  _DFILE  ; 400C  X   Address of Display File (screen data) in memory.
DF_CC:  dw  0       ; 400E      Address of PRINT position in display file. Can be poked so that PRINT output is sent elsewhere.
VARS:   dw  _VARS   ; 4010  X   Address of user program variables in memory.
DEST:   dw  0       ; 4012  N   Address of variable in assignment.
E_LINE: dw  _E_LINE ; 4014  X   Address of line being edited in memory.
CH_ADD: dw  0       ; 4016  X   Address of the next character to be interpreted: the character after the argument of PEEK,
                    ;                   or the ENTER/NEWLINE at the end of a POKE statement.
X_PTR:  dw  0       ; 4018      Address of the character preceding the [S] marker.
STKBOT: dw  0       ; 401A  X   Address of the Calculator stack in memory. This is where Basic does the math calculations.
STKEND: dw  0       ; 401C  X   End of the Calculator stack.
BREG:   db  0       ; 401E  N   Calculator’s b register.
MEM:    dw  0       ; 401F  N   Address of area used for calculator’s memory. (Usually MEMBOT but not always.)
        db  0       ; 4021      not used
DF_SZ:  db  0       ; 4022  X   The number of lines (including one blank line) in the lower part of the screen.
S_TOP:  dw  0       ; 4023      The number of the top program line in automatic listings.
LAST_K: dw  0       ; 4025  N   Shows which keys pressed
        db  0       ; 4027  N   Debounce status of keyboard.
MARGIN: db  0       ; 4028  N   Number of blank lines above or below picture: 55 in Britain (50Hz), 31 in America (60Hz).
NXTLIN: dw  0       ; 4029  X   Address of next program line to be executed.
OLDPPC: dw  0       ; 402B      Line number to which CONT jumps.
FLAGX:  db  0       ; 402D  N   Various flags.
STRLEN: dw  0       ; 402E  N   Length of string type designation in assignment.
T_ADDR: dw  0       ; 4030  N   Address of next item in syntax table.
SEED:   dw  0       ; 4032      The seed for RND. This is the variable that is set by RAND.
FRAMES: dw  $8000   ; 4034      Counts the frames displayed on the television. Bit 15 is 1. Bits 0 to 14 are decremented for each frame
                    ;           sent to the television. This can be used for timing, but PAUSE also uses it. PAUSE resets bit 15 to 0 and
                    ;           puts in bits 0 to 14 the length of the pause. When these have been counted down to zero, the pause stops.
                    ;           If the pause stops because of a key depression, bit 15 is set to 1 again.
COORDS: db  0       ; 4036      x-coordinate of last pointed PLOTted.
        db  0       ; 4037      y-coordinate of last pointed PLOTted.
PR_CC:  db  0       ; 4038      Less significant byte of address of next position for LPRINT to print at (in PRBUFF).
S_POSN: db  0       ; 4039  X   Column number for PRINT position.
        db  0       ; 403A  X   Line number for PRINT position.
CDFLAG: db  $80     ; 403B      Various flags. Bit 7 is set during compute and display (SLOW) mode.
PRBUFF: ds  33      ; 403C      Printer buffer (33rd character is ENTER/NEWLINE).
MEMBOT: ds  30      ; 405D  N   Calculator’s memory area; used to store numbers that cannot conveniently be put on the calculator stack.
        dw  0       ; 407B      not used

                    ;           X = The variable should not be poked because the system might crash.
                    ;           N = Poking the variable will have no lasting effect.

#assert $ == $407D


; --------------------------------------
; BASIC code and variables, Machine code
; --------------------------------------

#code _BASIC_INIT

        ; Open the BASIC REM statement

Program:        
Line1:          DEFB $00,$01                    ; Line 1
                DEFW Line1End-Line1Text         ; Line 1 length
Line1Text:      DEFB $EA                        ; REM             


; Start of test code
                LD      A, '*'
                RST     $0010
                RET



; ===========================================================
; End of BASIC REM statment containing eForth
; ===========================================================

#code   _BASIC_END

                ; Complete the REM statement

                DEFB $76                        ; Newline
Line1End:       
Line2:          DEFB $00,$02                    ; Line 2
                DEFW Line2End-Line2Text
Line2Text:      DEFB $F9,$D4                    ; RAND USR
                DEFB $1D,$22,$21,$1D,$20        ; 16514
                DEFB $7E                        ; Number
                DEFB $8F,$01,$04,$00,$00        ; Numeric encoding
                DEFB $76                        ; Newline
Line2End: 


#code _DFILE

        ; if saved in slow mode (CDFLAG bit 7 set) the display file must contain valid data

#if 0
        ; collapsed dfile:
        ds      25, opcode(halt)

#else
        ; inflated dfile:
        db      opcode(halt)
        rept 24
        ds      32,' '          ; note: or use $00: ' ' is charset translated to $00 by zasm
        db      opcode(halt)
        endm
#endif


#code _VARS

# assert        _VARS == _DFILE + 793

        ; add basic variables and/or machine code here
        ; if less than 16k are installed then the variables will be moved up and down
        ; as text is printed to the screen!

        db      $80             ; end-of-variables indicator


#code _E_LINE

        ; unsaved areas:
        ; (E_LINE) - (STKBOT)   Line being typed and work space
        ; (STKBOT) - (STKEND)   Calculator Stack
        ; (STKEND) - (ERR_SP)   Spare space and Z80 Machine Stack (sp)
        ; (ERR_SP) - (RAMTOP)   Gosub Stack
        ; (RAMTOP)              End of memory (address of last byte (incl.))
```

Paul

**Comment by pdr0663** [comment]
BTW this is wrong:

```
; (RAMTOP)              End of memory (address of last byte (incl.))
;
; value of RAMTOP:
;       $43FF = 17407 For 1k internal ram (ZX81)
;       $47FF = 18431 For 2k internal ram (TS1000)
;       $7fff = 32767 for 16k Ram Pack
;       $bfff = 49151 for 32k Ram Pack
;       $ffff = 65535 for 64k Ram Pack
```

RAMTOP is set by the ZX81 system to the first byte AFTER the last phesical memory address.

E.g. in a 16k system, RAMTOP is set to 32768, not 32767, so all the values above are incorrect. In that case, I don't know how a straight 64k system would be supported, as RAMTOP would need to be set to a value > 16-bits.

**Comment by Megatokio** [comment]
Thank you,
i didn't know this. i'll correct it! :-)
Kio !

**Comment by Megatokio** [comment]
Hi Paul,
i replied to one (now deleted?) comment directly. please tell me whether you received this email.
Kio !

**Comment by pdr0663** [comment]
Kio,

This is a reply directly from my email. If you want to use email directly,
my address is

***@***.***

Paul

**Comment by Megatokio** [comment]
> Kio, This is a reply directly from my email. If you want to use email directly, my address is ***@***.*** Paul

oh yes, gibhub protects us from any direct communicatrion...
i have set my email address to publically visible, maybe it is shown somewhere in my profile.

from my email:
