### ISSUE TITLE
Intel Hex files: Wrong origin

### ISSUE THREAD

**Issue by Mellvik** [Megatokio/zasm#9]
zasm generates an Intel Hex file with origin zero, regardless of the actual origin set in the code. The zero origin is hardcoded in the writeHexFile routine. The reasonable (and expected) behaviour would be to pick up the origin from the code.

**Comment by Megatokio** [comment]
hi, 
for roms this is exactly what you need, but i assume that you want to load the hex file into ram or an emulator. if so can you tell me your system setup and can you test changed output from zasm?

**Comment by Mellvik** [comment]
Thanks, I'm cross assembling for RAM - host MacOS.

I can test any ORG value, and btw the changes are clearly visible in the HEX file.

Thanks again for looking into this.

—Helge

**Comment by Megatokio** [comment]
We have a conflict between 'ram loaders' and 'eprom burners'. Ram loaders see cpu addresses and eprom burners see 'physical' addresses, e.g. if an eprom is mapped at $C000 then the ram loader wishes to know the $C000 while the eprom burner wishes to see $0000 for the start address. This cannot be universally solved, as e.g. eproms can be banked, thereby multiple pages show up at the same cpu address (not easily solvable for a ram loader anyway) while an eprom burner happily burns a single hex file with 4 pages of 16KB into one 64KB eprom, but it will probably not ignore an initial address offset ('org') but will start burning with this offset inside the eprom instead.

The only cases of concern are '#target bin', '#target rom' and files without '#target' which default to 'rom', when they are stored as Intel hex or Motorola S19 files which contain addresses.

Currently zasm does not store any initial address offset ('org') in an Intel hex or Motorla S19 file. This is suitable for eprom burners. 

Currently the only difference between '#target bin' and '#target rom' (incl. no '#target') is the default fill pattern for '.defs', which is $00 for 'bin' and $FF for 'rom'. 

### Possible solution:

- '#target rom' behavior will not change.
- '#target bin' behavior will not change but it will be deprecated. zasm prints a warning and suggests to use '#target ram' instead.
- A new '#target ram' is added which behaves like 'bin' but stores addresses starting at 'org'.
- If the source does not start with a '#target' instruction then zasm defaults to 'rom'. (no change)
Then if the output file is hex or s19 and the 'org' is not $0000 then zasm prints a warning and suggests to use '#target rom' or '#target ram' as desired.

**Comment by Mellvik** [comment]
Hi Kio,
This was indeed thorough. I support your proposal, and quite honestly my only requirement is the ability to set an ORiGin that gets reflected in the Intel Hex file.

I'm looking forward to the fix!

HS

**Comment by Megatokio** [comment]
hi,
i have pushed a new version which adds 'target ram' and also updated the Linux version on my website to version 4.2.7. 
please tell me whether this works and fixes your problem.
Kio!

**Comment by Mellvik** [comment]
Thank you Kim,
sorry for the long delay - this looks really good for my purposes. I appreciate the fix.

--Mellvik
